export type PhoneCountryOption = {
  code: string;
  dialCode: string;
  label: string;
  flag: string;
};

export const DEFAULT_PHONE_COUNTRY = 'EG';

export const PHONE_COUNTRY_OPTIONS = [
  { code: 'EG', dialCode: '+20', label: 'Egypt', flag: '🇪🇬' },
  { code: 'US', dialCode: '+1', label: 'United States', flag: '🇺🇸' },
  { code: 'CA', dialCode: '+1', label: 'Canada', flag: '🇨🇦' },
  { code: 'GB', dialCode: '+44', label: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE', dialCode: '+49', label: 'Germany', flag: '🇩🇪' },
  { code: 'FR', dialCode: '+33', label: 'France', flag: '🇫🇷' },
  { code: 'IT', dialCode: '+39', label: 'Italy', flag: '🇮🇹' },
  { code: 'ES', dialCode: '+34', label: 'Spain', flag: '🇪🇸' },
  { code: 'NL', dialCode: '+31', label: 'Netherlands', flag: '🇳🇱' },
  { code: 'BE', dialCode: '+32', label: 'Belgium', flag: '🇧🇪' },
  { code: 'CH', dialCode: '+41', label: 'Switzerland', flag: '🇨🇭' },
  { code: 'AT', dialCode: '+43', label: 'Austria', flag: '🇦🇹' },
  { code: 'SE', dialCode: '+46', label: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', dialCode: '+47', label: 'Norway', flag: '🇳🇴' },
  { code: 'DK', dialCode: '+45', label: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', dialCode: '+358', label: 'Finland', flag: '🇫🇮' },
  { code: 'IE', dialCode: '+353', label: 'Ireland', flag: '🇮🇪' },
  { code: 'PT', dialCode: '+351', label: 'Portugal', flag: '🇵🇹' },
  { code: 'GR', dialCode: '+30', label: 'Greece', flag: '🇬🇷' },
  { code: 'TR', dialCode: '+90', label: 'Turkey', flag: '🇹🇷' },
  { code: 'SA', dialCode: '+966', label: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'AE', dialCode: '+971', label: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'QA', dialCode: '+974', label: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', dialCode: '+965', label: 'Kuwait', flag: '🇰🇼' },
  { code: 'BH', dialCode: '+973', label: 'Bahrain', flag: '🇧🇭' },
  { code: 'OM', dialCode: '+968', label: 'Oman', flag: '🇴🇲' },
  { code: 'JO', dialCode: '+962', label: 'Jordan', flag: '🇯🇴' },
  { code: 'LB', dialCode: '+961', label: 'Lebanon', flag: '🇱🇧' },
  { code: 'MA', dialCode: '+212', label: 'Morocco', flag: '🇲🇦' },
  { code: 'TN', dialCode: '+216', label: 'Tunisia', flag: '🇹🇳' },
  { code: 'DZ', dialCode: '+213', label: 'Algeria', flag: '🇩🇿' },
  { code: 'ZA', dialCode: '+27', label: 'South Africa', flag: '🇿🇦' },
  { code: 'NG', dialCode: '+234', label: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', dialCode: '+254', label: 'Kenya', flag: '🇰🇪' },
  { code: 'IN', dialCode: '+91', label: 'India', flag: '🇮🇳' },
  { code: 'PK', dialCode: '+92', label: 'Pakistan', flag: '🇵🇰' },
  { code: 'BD', dialCode: '+880', label: 'Bangladesh', flag: '🇧🇩' },
  { code: 'ID', dialCode: '+62', label: 'Indonesia', flag: '🇮🇩' },
  { code: 'MY', dialCode: '+60', label: 'Malaysia', flag: '🇲🇾' },
  { code: 'SG', dialCode: '+65', label: 'Singapore', flag: '🇸🇬' },
  { code: 'PH', dialCode: '+63', label: 'Philippines', flag: '🇵🇭' },
  { code: 'TH', dialCode: '+66', label: 'Thailand', flag: '🇹🇭' },
  { code: 'VN', dialCode: '+84', label: 'Vietnam', flag: '🇻🇳' },
  { code: 'CN', dialCode: '+86', label: 'China', flag: '🇨🇳' },
  { code: 'JP', dialCode: '+81', label: 'Japan', flag: '🇯🇵' },
  { code: 'KR', dialCode: '+82', label: 'South Korea', flag: '🇰🇷' },
  { code: 'AU', dialCode: '+61', label: 'Australia', flag: '🇦🇺' },
  { code: 'NZ', dialCode: '+64', label: 'New Zealand', flag: '🇳🇿' },
  { code: 'BR', dialCode: '+55', label: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', dialCode: '+52', label: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', dialCode: '+54', label: 'Argentina', flag: '🇦🇷' },
  { code: 'CL', dialCode: '+56', label: 'Chile', flag: '🇨🇱' },
  { code: 'CO', dialCode: '+57', label: 'Colombia', flag: '🇨🇴' },
  { code: 'PE', dialCode: '+51', label: 'Peru', flag: '🇵🇪' },
  { code: 'PL', dialCode: '+48', label: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', dialCode: '+420', label: 'Czech Republic', flag: '🇨🇿' },
  { code: 'RO', dialCode: '+40', label: 'Romania', flag: '🇷🇴' },
  { code: 'HU', dialCode: '+36', label: 'Hungary', flag: '🇭🇺' },
  { code: 'IL', dialCode: '+972', label: 'Israel', flag: '🇮🇱' },
  { code: 'GH', dialCode: '+233', label: 'Ghana', flag: '🇬🇭' }
] as const satisfies readonly PhoneCountryOption[];
